trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: UpdateStack
  displayName: Update CloudFormation stack
  jobs: 
  - job: Update
    displayName: Update
    steps:
    - task: CloudFormationCreateOrUpdateStack@1
      inputs:
        awsCredentials: 'AWS'
        regionName: 'eu-central-1'
        stackName: 'docker-dotnet-api'
        templateFile: infrastructure/infrastructure.yaml
        capabilityIAM: true
        capabilityNamedIAM: true
