apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::358599436160:role/dotnet-docker-InstanceRole-ZDJ2CG8E6F5C
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
   mapUsers: |
      - userarn: arn:aws:iam::358599436160:user/github-user
      username: admin
      groups:
          - system:masters
