Description: Creating an EC2 instance.
Resources:
  MainSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the API instances.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  MainInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ac05733838eabc06
      InstanceType: t2.micro
