name: CI/CD

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run:  docker build -t ${{ secrets.DOCKER_USERNAME }}/dotnet-api:$(date +%s) .
    
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push the Docker image
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/dotnet-api
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: eu-central-1
        
    - name: Add AWS-IAM-Authenticator
      run: |
        curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$HOME/bin:$PATH
        echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
      
    - name: Deploy to AWS
      run: |
        aws eks --region eu-central-1 update-kubeconfig --name ${{ secrets.EKS_CLUSTER }}
        kubectl apply -f aws/aws-auth-cm.yaml
        kubectl set image deployments/dotnet-api dotnet-api=${{ secrets.DOCKER_USERNAME }}/dotnet-api
        kubectl apply -f aws/cluster-deployment.yaml
        chmod +x aws/aws-cloudformation.sh
        aws/aws-cloudformation.sh deploy --stack-name dotnet-docker --template-file infrastructure/infrastructure.yaml --parameter-overrides DockerUsername=${{ secrets.DOCKER_USERNAME }} DockerPassword=${{ secrets.DOCKER_PASSWORD }} --capabilities CAPABILITY_IAM
        
